# Generated by Django 4.0 on 2021-12-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('images', models.ImageField(upload_to='images', verbose_name='Изображения')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('lte_exists', models.BooleanField(null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
