# Generated by Django 4.0 on 2021-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='images',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Изображения'),
        ),
    ]
