# Generated by Django 4.0 on 2021-12-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
