# Generated by Django 4.0 on 2021-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phone_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='images',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображения'),
        ),
    ]
