# Generated by Django 4.0 on 2021-12-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
